version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: dishcovery-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: "123"
      MYSQL_DATABASE: DISHCOVERY_DEV
    ports:
      - "8080:3306"
    volumes:
      # Persist data between container restarts
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: